uses: "ScholliYT/Broken-Links-Crawler-Action@v3"
with:
  website_url: "https://www.bankitamas.hu"
  include_url_prefix: "https://www.bankitamas.hu"
  resolve_before_filtering: "true"
  verbose: "true"
  max_retry_time: 10
  max_retries: 1
  max_depth: 1
